const bcrypt = require('bcrypt');
const jwt = require('jsonwebtoken');
require('dotenv').config();
const SECRET = process.env.SECRET || 'mysecret';
const db = {};
const Users = {};
const roles = {
  user: ['read'],
  editor: ['read', 'create', 'update'],
  admin: ['read', 'create', 'update', 'delete'],
};
/*
  db
  {
    'mahmoud':{
      username:"mahmoud",
      password:"jkabndajnsdjkasndkjlasndasjndasjkdn;asjkndajksndasjnd"
    }
  }
 */
//signup
Users.save = async function (record) {
  /**
   * record
   * {username:"mahmoud",password:"1234"}
   */
  if (!db[record.username]) {
    record.password = await bcrypt.hash(record.password, 5);
    db[record.username] = record;
    return record;
  }
  return Promise.reject(); // ==>.catch
};
// user:pass
//signin
Users.authenticateBasic = async function (user, pass) {
  const valid = await bcrypt.compare(pass, db[user].password);
  return valid ? db[user] : Promise.reject('wrong password');
};
//signin/signup
Users.generateToken = function (user) {
  // FOR TESTING ONLY OUR USERS WILL SEND THE ROLE FROM THE SIGNUP and user.role= [user,admin,editor]
  // user.role === user
  // capabilities === roles[user.role] ===== ['read'] OR ['read', 'create', 'update']
  const userData = { username: user.username, capabilities: roles[user.role] };
  const token = jwt.sign(userData, SECRET);
  return token;
};
// to verify the token that the user used from the client that was generated by jwt
Users.authenticateToken = async function (token) {
  // akjsndlaksnd.34naliendiasnd.3nksabndfw334ng
  try {
    const tokenObject = await jwt.verify(token, SECRET);
    // tokenObject = {username:"mahmoud",iat:91223238}
    if (db[tokenObject.username]) {
      return Promise.resolve(tokenObject);
    } else {
      return Promise.reject('User is not found!');
    }
  } catch (e) {
    return Promise.reject(e.message);
  }
};
//find all
Users.list = () => db;
module.exports = Users;
